#!/bin/bash

# ----------------------------------------------------------------------------
# FOR MITgcm COMPILATION ON OSC CLUSTER SAL 
# Last updated: HP 04/08/10
# ----------------------------------------------------------------------------

FC=mpiifort
CC=mpiicc
LINK=mpiifort

CPP='/usr/bin/cpp -P -traditional'
MPI='true'

#FFLAGS='-fPIC -r8 -i4 -WB -convert big_endian -assume byterecl'
FFLAGS='-r8 -i4 -WB -convert big_endian -assume byterecl -mcmodel=medium -shared-intel -g -I/share/software/intel/impi/4.0.3.008/intel64/include' 
FOPTIM='-O3 '


F90FLAGS=$FFLAGS
F90OPTIM=$FOPTIM

#CFLAGS='-O3 -xssse3 -ip -fPIC'
CFLAGS='-03 -ip'

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4'

# --------------------------
# INCLUDE NETCDF DIRECTORIES
# --------------------------
INCLUDEDIRS=""
INCLUDES="-I/share/local/include"
LIBS="-L/share/local/lib -lnetcdf -lmpi"

# -----------------------
# INCLUDE MPI DIRECTORIES
# -----------------------
INCLUDES="$INCLUDES -I/usr/include -I/share/software/intel/impi/4.0.3.008/intel64/include"
INCLUDEDIRS="/usr/include"
MPIINCLUDEDIR="/usr/include"
LIBS="$LIBS -L/usr/lib64/"
#MPI_HEADER_FILES='/usr/include/mpif.h /usr/include/mpiof.h /usr/include/mpif_parameters.h'
#MPI_HEADER_FILES_INC='/usr/include/mpif.h /usr/include/mpiof.h /usr/include/mpif_parameters.h'
MPI_HEADER_FILES='mpif.h mpiof.h mpif_parameters.h'
MPI_HEADER_FILES_INC='mpi_headers/mpif.h mpi_headers/mpiof.h mpi_headers/mpif_parameters.h'

#
#INCLUDES="-I/usr/include -I/home/system/software/redqueen/libs/netcdf-4.0/include"
#LIBS="-L/home/system/software/redqueen/libs/netcdf-4.0/lib -lnetcdf -lmpi"


